//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryConsole.BookDatabaseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookDatabaseService.IBookDatabaseService")]
    public interface IBookDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IBookDatabaseService/GetBooksResponse")]
        System.Collections.Generic.List<MovieDatabase.Models.Book> GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IBookDatabaseService/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Book>> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/AddBook", ReplyAction="http://tempuri.org/IBookDatabaseService/AddBookResponse")]
        void AddBook(MovieDatabase.Models.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/AddBook", ReplyAction="http://tempuri.org/IBookDatabaseService/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(MovieDatabase.Models.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/DeleteBook", ReplyAction="http://tempuri.org/IBookDatabaseService/DeleteBookResponse")]
        void DeleteBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/DeleteBook", ReplyAction="http://tempuri.org/IBookDatabaseService/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/EditBook", ReplyAction="http://tempuri.org/IBookDatabaseService/EditBookResponse")]
        void EditBook(MovieDatabase.Models.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/EditBook", ReplyAction="http://tempuri.org/IBookDatabaseService/EditBookResponse")]
        System.Threading.Tasks.Task EditBookAsync(MovieDatabase.Models.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetById", ReplyAction="http://tempuri.org/IBookDatabaseService/GetByIdResponse")]
        MovieDatabase.Models.Book GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetById", ReplyAction="http://tempuri.org/IBookDatabaseService/GetByIdResponse")]
        System.Threading.Tasks.Task<MovieDatabase.Models.Book> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookDatabaseServiceChannel : LibraryConsole.BookDatabaseService.IBookDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookDatabaseServiceClient : System.ServiceModel.ClientBase<LibraryConsole.BookDatabaseService.IBookDatabaseService>, LibraryConsole.BookDatabaseService.IBookDatabaseService {
        
        public BookDatabaseServiceClient() {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookDatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MovieDatabase.Models.Book> GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Book>> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public void AddBook(MovieDatabase.Models.Book book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(MovieDatabase.Models.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void DeleteBook(int id) {
            base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(int id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public void EditBook(MovieDatabase.Models.Book book) {
            base.Channel.EditBook(book);
        }
        
        public System.Threading.Tasks.Task EditBookAsync(MovieDatabase.Models.Book book) {
            return base.Channel.EditBookAsync(book);
        }
        
        public MovieDatabase.Models.Book GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<MovieDatabase.Models.Book> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
