//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookDatabaseService")]
    public interface IBookDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IBookDatabaseService/GetBooksResponse")]
        System.Collections.Generic.List<MovieDatabase.Models.Book> GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetBooks", ReplyAction="http://tempuri.org/IBookDatabaseService/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Book>> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetAuthors", ReplyAction="http://tempuri.org/IBookDatabaseService/GetAuthorsResponse")]
        System.Collections.Generic.List<MovieDatabase.Models.Author> GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/GetAuthors", ReplyAction="http://tempuri.org/IBookDatabaseService/GetAuthorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Author>> GetAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/AddBook", ReplyAction="http://tempuri.org/IBookDatabaseService/AddBookResponse")]
        void AddBook(MovieDatabase.Models.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookDatabaseService/AddBook", ReplyAction="http://tempuri.org/IBookDatabaseService/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(MovieDatabase.Models.Book book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookDatabaseServiceChannel : LibraryConsole.ServiceReference1.IBookDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookDatabaseServiceClient : System.ServiceModel.ClientBase<LibraryConsole.ServiceReference1.IBookDatabaseService>, LibraryConsole.ServiceReference1.IBookDatabaseService {
        
        public BookDatabaseServiceClient() {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookDatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookDatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MovieDatabase.Models.Book> GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Book>> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public System.Collections.Generic.List<MovieDatabase.Models.Author> GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MovieDatabase.Models.Author>> GetAuthorsAsync() {
            return base.Channel.GetAuthorsAsync();
        }
        
        public void AddBook(MovieDatabase.Models.Book book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(MovieDatabase.Models.Book book) {
            return base.Channel.AddBookAsync(book);
        }
    }
}
